config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

  # dev環境であればat以下のURLでLetterOpenerwebの内容が見れるようになるという設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # homeコントラーラのindexアクションを実行
  # get '/' => 'home#index'

  # root_pathの設定(/のパス)
  root to: 'articles#index'

  # URLの生成（入れ子構造になっている）
  resources :articles

  # ユーザーごとのアカウント詳細ページと、それに関するフォロー・アンフォロー
  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  # ログインユーザ用のルーティング
  scope module: :apps do
    resources :favorites, only: [:index] # いいね一覧 (中級編 day25-4)
    resource :profile, only: [:show, :edit, :update]
    resource :timeline, only: [:show]
  end

  # APIに関するアクションのルーティング
  namespace :api, defaults: {format: :json} do
    scope '/articles/:article_id' do
      resources :comments, only: [:index, :new, :create]
      resource :like, only: [:show, :create, :destroy]
    end
  end
  
end

app/views/layouts/_footer.html.haml
%footer.footer-container
  - if I18n.locale == :en
    = link_to '日本語', url_for(locale: :ja)
  - else
    = link_to 'English', url_for(locale: :en)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlogApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# ヘッダー
    %header.header
      .header_logos

        -# 指定したURLが、現在表示されているかチェック
        - if !current_page?(root_path) # 現在のページがroot_pathでなければ
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle
          = link_to 'BlogApp', root_path

      -# ログイン時の表示とそうでない時の表示
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'お気に入り', favorites_path
            = link_to 'ログアウト', destroy_user_session_path, data: {method: 'delete'}
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'

    -# フラッシュ
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value

  
    = yield
    = render 'layouts/footer'